### ISSUE TITLE
delete account

### ISSUE THREAD

**Issue by raspberri05** [personafm/persona.fm#177]

**Comment by JessyWaweru** [comment]
Hi!What exactly should be done here?I'd love to try

**Comment by raspberri05** [comment]
A feature that deletes the user from the database (add a delete button in the settings page). It should delete the user from the database, clear all cookies for the site, and redirect to the index (/) route. Consulting https://orm.drizzle.team/docs/overview to understand how to write the code to delete a database record will be helpful. You can see how the database is structured in the schema file
