### ISSUE TITLE
Gradient not extending all the way horizontally

### ISSUE THREAD

**Issue by raspberri05** [personafm/persona.fm#271]
**Describe the bug**
The gradient background should span the full width of the screen but it does not on large screen widths

**To Reproduce**
1. Go to any page
3. Make window horizontally large

**Expected behavior**
Gradient should span the full page width

**Screenshots**
![image](https://github.com/user-attachments/assets/b94ab44c-80b2-4ff1-b56b-144ebc8d4540)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 131

**Additional context**
N/A

**Comment by slusy** [comment]
Hey, I would like to work on this

**Comment by raspberri05** [comment]
I went ahead and assigned you to this issue. Feel free to submit your changes via pull request once you are ready. Also, please consider starring this repository as it will enable more developers to find and contribute to this project.
