### ISSUE TITLE
Add a contact form UI to the contact us page

### ISSUE THREAD

**Issue by raspberri05** [personafm/persona.fm#274]
**Is your feature request related to a problem? Please describe.**
It would be easier for users to be able to submit a contact form instead of having to open an email client separately to send the email

**Describe the solution you'd like**
Implement a the UI for a contact form using Shadcn ui components

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by raspberri05** [comment]
Use this link for reference on making a form https://ui.shadcn.com/docs/components/form
There should be a field for email address and a field for message

**Comment by Agastya18** [comment]
hi @raspberri05 ,I’d love to connect with you to discuss Persona.fm and explore ways to contribute more effectively in the future.
