### ISSUE TITLE
Add contact form backend 

### ISSUE THREAD

**Issue by raspberri05** [personafm/persona.fm#275]
**Is your feature request related to a problem? Please describe.**
It would be easier for users to be able to submit a contact form instead of having to open an email client separately to send the email

**Describe the solution you'd like**
Implement the backend route for a contact form that uses nodemailer to send an email

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Harshvardhan1012** [comment]
Hey Can you assign this issue to me!

**Comment by raspberri05** [comment]
I went ahead and assigned you to this issue. Feel free to submit your changes via pull request once you are ready. Also, please consider starring this repository as it will enable more developers to find and contribute to this project.

There will be a email field and message body field. This issue is only for the backend portion, so no frontend work needs to be done for it. You should follow  the route conventions as seen in `app/api`
